-- phpMyAdmin SQL Dump
-- version 4.7.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Apr 22, 2019 at 02:53 PM
-- Server version: 5.6.40-84.0-log
-- PHP Version: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `war3vods_website`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `adminid` int(255) NOT NULL,
  `adminname` text NOT NULL,
  `adminpass` text NOT NULL,
  `str` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`adminid`, `adminname`, `adminpass`, `str`) VALUES
(1, 'Alex', 'YWoMp2PY/ReSI', 'YWxleA=='),
(2, 'Dave', 'YWKZZNKtxXZAY', 'YWxleA==');

-- --------------------------------------------------------

--
-- Table structure for table `FrontPage`
--

CREATE TABLE `FrontPage` (
  `frontpageid` int(255) NOT NULL,
  `frontpagevideo` text NOT NULL,
  `frontpagetitle` text NOT NULL,
  `frontpagedes` text NOT NULL,
  `TournamentID` int(11) NOT NULL,
  `DateAdded` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `FrontPage`
--

INSERT INTO `FrontPage` (`frontpageid`, `frontpagevideo`, `frontpagetitle`, `frontpagedes`, `TournamentID`, `DateAdded`) VALUES
(3, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/AXjoT6M10bk\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Lyn(O) vs FoCuS(O)', '<p>Quarter Finals</p>\r\n<p>Best of 5</p>\r\n<p>Warcraft Gold League 2018 Winter Season</p>', 1, ''),
(4, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/UXJXe3Ov22I\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Moon(N) vs Fly100%(O)', '<p>Quarter Finals</p>\r\n<p>Best of 5</p>\r\n<p>Warcraft Gold League 2018 Winter Season</p>', 1, ''),
(5, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/XnWHtPWVEDA\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Colouful(H) vs Infi(N)', '<p>Quarter Finals</p>\r\n<p>Best of 5</p>\r\n<p>Warcraft Gold League 2018 Winter Season</p>', 1, ''),
(6, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/JBsf1Sp844g\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'LawLiet(N) vs Foggy(N)', '<p>Quarter Finals</p>\r\n<p>Best of 5</p>\r\n<p>Warcraft Gold League 2018 Winter Season</p>', 1, ''),
(7, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/mFDt8Gcgdf4\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Lyn(O) vs Moon(N)', '<p>Semifinals</p>\r\n<p>Best of 5</p>\r\n<p>Warcraft Gold League 2018 Winter Season</p>', 1, ''),
(8, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/kHUSA_Jmiv8\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Infi(H) vs Foggy(N)', '<p>Semifinals</p>\r\n<p>Best of 5</p>\r\n<p>Warcraft Gold League 2018 Winter Season</p>', 1, ''),
(9, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/1qmiWSaAiPM\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Lyn <img src=\"img/warcrafticons/orc/grunt.png\" style=\"width:42px;height:42px;border:0;\"> vs Infi <img src=\"img/warcrafticons/nightelf/archer.png\" style=“width:42px;height:42px;border:0;\">\r\n', '<p>Warcraft Gold League 2018 Winter Season</p>\r\n<p>3rd Place Match</p>\r\n<p>Best of 5</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/orc/blademaster.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/shadowshaman.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n\r\n', 1, ''),
(10, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/dnZ82yZ5438\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Moon <img src=\"img/warcrafticons/nightelf/archer.png\" style=\"width:42px;height:42px;border:0;\"> vs Foggy <img src=\"img/warcrafticons/nightelf/archer.png\" style=“width:42px;height:42px;border:0;\">\r\n\r\n', '<p>Warcraft Gold League 2018 Winter Season</p>\r\n<p>Finals</p>\r\n<p>Best of 7</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n', 1, ''),
(11, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/96rVkNAO6qA\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Check <img src=\"img/warcrafticons/nightelf/archer.png\" style=\"width:42px;height:42px;border:0;\"> vs Sini <img src=\"img/warcrafticons/nightelf/archer.png\" style=“width:42px;height:42px;border:0;\">', '<p>Group A - Qualifier</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p>NeXT 2018 Winter</p>\r\n\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\nvs\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 2, ''),
(12, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/SqFaXXoq4Sk\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'TH000 <img src=\"img/warcrafticons/human/footmen.png\" style=\"width:42px;height:42px;border:0;\"> vs Sok <img src=\"img/warcrafticons/human/footmen.png\" style=“width:42px;height:42px;border:0;\">', '<p>Group B - Qualifier</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p>NeXT 2018 Winter</p>\r\n\r\n<p>\r\n<img src=\"img/warcrafticons/human/archmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/mountainking.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\nvs\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/human/archmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 2, ''),
(13, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/axHWTyqLIt4\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'TH000 <img src=\"img/warcrafticons/human/footmen.png\" style=\"width:42px;height:42px;border:0;\"> vs FoCuS <img src=\"img/warcrafticons/orc/grunt.png\" style=“width:42px;height:42px;border:0;\">\r\n', '<p>Group B - Qualifier</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p>NeXT 2018 Winter</p>\r\n\r\n<p>\r\n<img src=\"img/warcrafticons/human/archmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/bloodmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/mountainking.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\nvs\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/orc/blademaster.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/shadowshaman.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 2, ''),
(14, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/xDCF5wUU4Ug\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'FoCuS <img src=\"img/warcrafticons/orc/grunt.png\" style=\"width:42px;height:42px;border:0;\"> vs Sok <img src=\"img/warcrafticons/human/footmen.png\" style=“width:42px;height:42px;border:0;\">', '<p>Group B - Qualifier</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p>NeXT 2018 Winter</p>\r\n\r\n<p>\r\n<img src=\"img/warcrafticons/human/archmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/beastmaster.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/mountainking.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\nvs\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/orc/blademaster.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/shadowshaman.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 2, ''),
(15, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/hc7UFvRt0tM\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Life <img src=\"img/warcrafticons/nightelf/archer.png\" style=\"width:42px;height:42px;border:0;\"> vs Chaemiko <img src=\"img/warcrafticons/human/footmen.png\" style=“width:42px;height:42px;border:0;\">', '<p>Group C - Qualifier</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p>NeXT 2018 Winter</p>\r\n\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/demonhunter.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\nvs\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/human/archmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/mountainking.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 2, ''),
(16, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/dZOCtYSgC-E\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'WFZ <img src=\"img/warcrafticons/undead/ghoul.png\" style=\"width:42px;height:42px;border:0;\"> vs Chaemiko <img src=\"img/warcrafticons/human/footmen.png\" style=\"width:42px;height:42px;border:0;\">\r\n', '<p>Group C - Qualifier</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p>NeXT 2018 Winter</p>\r\n\r\n<p>\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/darkranger.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\nvs\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/human/archmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/mountainking.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/paladin.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/bloodmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 2, ''),
(17, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/HTcNrmDyX2A\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Life <img src=\"img/warcrafticons/nightelf/archer.png\" style=\"width:42px;height:42px;border:0;\"> vs WFZ <img src=\"img/warcrafticons/undead/ghoul.png\" style=\"width:42px;height:42px;border:0;\">\r\n\r\n', '<p>Group C - Qualifier</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p>NeXT 2018 Winter</p>\r\n\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\nvs\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/darkranger.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 2, ''),
(18, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/vXY3eVw5XeE\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Lucifer <img src=\"img/warcrafticons/undead/ghoul.png\" style=\"width:42px;height:42px;border:0;\"> vs Colorful <img src=\"img/warcrafticons/nightelf/archer.png\" style=\"width:42px;height:42px;border:0;\">\r\n', '<p>Group D - Qualifier</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p>NeXT 2018 Winter</p>\r\n\r\n<p>\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/dreadlord.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/darkranger.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/tinker.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\nvs\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 2, ''),
(19, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/ALKW8XEhSuA\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Lucifer <img src=\"img/warcrafticons/undead/ghoul.png\" style=\"width:42px;height:42px;border:0;\"> vs WhO <img src=\"img/warcrafticons/orc/grunt.png\" style=\"width:42px;height:42px;border:0;\">\r\n\r\n', '<p>Group D - Qualifier</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p>NeXT 2018 Winter</p>\r\n\r\n<p>\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/darkranger.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\nvs\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/orc/farseer.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/taurenchief.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 2, ''),
(20, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/q9LEgdCl0iY\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Lucifer <img src=\"img/warcrafticons/undead/ghoul.png\" style=\"width:42px;height:42px;border:0;\"> vs Zhou_Xixi <img src=\"img/warcrafticons/nightelf/archer.png\" style=\"width:42px;height:42px;border:0;\">', '<p>Group D - Qualifier</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p>NeXT 2018 Winter</p>\r\n\r\n<p>\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/tinker.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\nvs\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/nightelf/demonhunter.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 2, ''),
(21, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/cGsqb709ttM\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Orcworker <img src=\"img/warcrafticons/orc/grunt.png\" style=\"width:42px;height:42px;border:0;\"> vs XiaoKK <img src=\"img/warcrafticons/orc/grunt.png\" style=“width:42px;height:42px;border:0;\">', '<p>Quarterfinals</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p>One Belt One Road</p>\r\n\r\n<p>\r\n<img src=\"img/warcrafticons/orc/blademaster.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/shadowshaman.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\nvs\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/orc/blademaster.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/shadowshaman.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 3, ''),
(22, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/icjtOSGymf4\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'WFZ <img src=\"img/warcrafticons/undead/ghoul.png\" style=\"width:42px;height:42px;border:0;\"> vs Zhou_Xixi <img src=\"img/warcrafticons/nightelf/archer.png\" style=“width:42px;height:42px;border:0;\">', '<p>Quarterfinals</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p>One Belt One Road</p>\r\n\r\n<p>\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/tinker.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\nvs\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/nightelf/demonhunter.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/panda.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 3, ''),
(23, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/ppPf5VLatko\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Moon <img src=\"img/warcrafticons/nightelf/archer.png\" style=\"width:42px;height:42px;border:0;\"> vs tbc_bm <img src=\"img/warcrafticons/undead/ghoul.png\" style=“width:42px;height:42px;border:0;\">', '<p>Quarterfinals</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p>One Belt One Road</p>\r\n<p>\r\nHeroes Used\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 3, ''),
(24, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/1C_j-21atY8\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Lyn <img src=\"img/warcrafticons/orc/grunt.png\" style=\"width:42px;height:42px;border:0;\"> vs Colorful <img src=\"img/warcrafticons/nightelf/archer.png\" style=“width:42px;height:42px;border:0;\">', '<p>One Belt One Road</p>\r\n\r\n<p>Quarterfinals</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/orc/blademaster.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/shadowshaman.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/taurenchief.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 3, ''),
(25, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/XakiGyWiE4U\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'WFZ <img src=\"img/warcrafticons/undead/ghoul.png\" style=\"width:42px;height:42px;border:0;\"> vs KiaoKK <img src=\"img/warcrafticons/orc/grunt.png\" style=“width:42px;height:42px;border:0;\">', '<p>One Belt One Road</p>\r\n\r\n<p>Semifinals</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/tinker.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/dreadlord.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/orc/farseer.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/taurenchief.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 3, ''),
(26, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/nZqpltTn9lg\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Moon <img src=\"img/warcrafticons/nightelf/archer.png\" style=\"width:42px;height:42px;border:0;\"> vs Lyn <img src=\"img/warcrafticons/orc/grunt.png\" style=“width:42px;height:42px;border:0;\">', '<p>One Belt One Road</p>\r\n\r\n<p>Quarterfinals</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/orc/blademaster.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/shadowshaman.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/taurenchief.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 3, ''),
(27, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/knfsgiQ112Q\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Lyn <img src=\"img/warcrafticons/orc/grunt.png\" style=\"width:42px;height:42px;border:0;\"> vs KiaoKK <img src=\"img/warcrafticons/orc/grunt.png\" style=“width:42px;height:42px;border:0;\">', '<p>One Belt One Road</p>\r\n\r\n<p>Game for 3rd Place</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/orc/blademaster.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/shadowshaman.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/orc/blademaster.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/shadowshaman.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>', 3, ''),
(28, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/j3i-O2PPZIo\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Moon <img src=\"img/warcrafticons/nightelf/archer.png\" style=\"width:42px;height:42px;border:0;\"> vs WFZ <img src=\"img/warcrafticons/undead/ghoul.png\" style=“width:42px;height:42px;border:0;\">', '<p>One Belt One Road</p>\r\n\r\n<p>Grandfinal</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/tinker.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/dreadlord.png\" style=\"width:25px;height:25px;border:0;\">', 3, ''),
(29, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/7CQZfCboLag\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'TH000 <img src=\"img/warcrafticons/human/footmen.png\" style=\"width:42px;height:42px;border:0;\"> vs Foggy <img src=\"img/warcrafticons/nightelf/archer.png\" style=“width:42px;height:42px;border:0;\">', '<p>W-League 2018 Super League</p>\r\n\r\n<p>Playday 11</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/human/archmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/mountainking.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p><u>\r\nMaps\r\n</p></u>\r\n<p>Terenas Stand</p>\r\n<p>Echo Isles</p>', 4, ''),
(30, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/gqkE-WRbsKE\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Moon <img src=\"img/warcrafticons/nightelf/archer.png\" style=\"width:42px;height:42px;border:0;\"> vs TH000 <img src=\"img/warcrafticons/human/footmen.png\" style=“width:42px;height:42px;border:0;\">', '<p>W-League 2018 Super League</p>\r\n\r\n<p>Playday 11</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/human/archmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/mountainking.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p><u>\r\nMaps\r\n</p></u>\r\n<p>Last Refuge</p>\r\n<p>Terenas Stand</p>', 4, ''),
(31, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/KSeE26Gx0Q4\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Foggy <img src=\"img/warcrafticons/nightelf/archer.png\" style=\"width:42px;height:42px;border:0;\"> vs FoCuS <img src=\"img/warcrafticons/orc/grunt.png\" style=“width:42px;height:42px;border:0;\">', '<p>W-League 2018 Super League</p>\r\n\r\n<p>Playday 11</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/orc/blademaster.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/shadowshaman.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/medusa.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p><u>\r\nMaps\r\n</p></u>\r\n<p>Echo Isles</p>\r\n<p>Ancient Isles</p>\r\n', 4, ''),
(32, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/_Lif17riGto\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'TH000 <img src=\"img/warcrafticons/human/footmen.png\" style=\"width:42px;height:42px;border:0;\"> vs Infi <img src=\"img/warcrafticons/human/footmen.png\" style=“width:42px;height:42px;border:0;\">', '<p>Super WGL</p>\r\n\r\n<p>Finals</p>\r\n\r\n<p>Best of 5</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/human/archmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/mountainking.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/human/archmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/mountainking.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p><u>\r\nMaps\r\n</p></u>\r\n<p>Last Refuge</p>\r\n<p>Concealed Hill</p>\r\n<p>Amazonia</p>\r\n\r\n', 5, ''),
(33, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/DlRhj9Olwlk\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Sniq <img src=\"img/warcrafticons/nightelf/archer.png\" style=\"width:42px;height:42px;border:0;\"> & Jon <img src=\"img/warcrafticons/undead/ghoul.png\" style=\"width:42px;height:42px;border:0;\"> vs Patitofeo <img src=\"img/warcrafticons/undead/ghoul.png\" style=“width:42px;height:42px;border:0;\"> & Wopy <img src=\"img/warcrafticons/orc/grunt.png\" style=“width:42px;height:42px;border:0;\">', '<p>Ugri\'s 2v2 Challenge</p>\r\n\r\n<p>Round 1</p>\r\n\r\n<p>Best of 1</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/blademaster.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/shadowshaman.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p><u>\r\nMaps\r\n</p></u>\r\n<p>Southfury River</p>', 6, ''),
(34, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/yJyxInhndvo\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Happy <img src=\"img/warcrafticons/undead/ghoul.png\" style=\"width:42px;height:42px;border:0;\"> & Cash <img src=\"img/warcrafticons/orc/grunt.png\" style=\"width:42px;height:42px;border:0;\"> vs LawLiet <img src=\"img/warcrafticons/nightelf/archer.png\" style=“width:42px;height:42px;border:0;\"> & FoCuS <img src=\"img/warcrafticons/orc/grunt.png\" style=“width:42px;height:42px;border:0;\">', '<p>Ugri\'s 2v2 Challenge</p>\r\n\r\n<p>Round 2</p>\r\n\r\n<p>Best of 1</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/cryptlord.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/taurenchief.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/farseer.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/taurenchief.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p><u>\r\nMaps\r\n</p></u>\r\n<p>Sherbrooke Hills</p>', 6, ''),
(35, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/8q6StarosrA\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Happy <img src=\"img/warcrafticons/undead/ghoul.png\" style=\"width:42px;height:42px;border:0;\"> & Cashf <img src=\"img/warcrafticons/orc/grunt.png\" style=\"width:42px;height:42px;border:0;\"> vs Foggy <img src=\"img/warcrafticons/nightelf/archer.png\" style=“width:42px;height:42px;border:0;\"> & HawK <img src=\"img/warcrafticons/human/footmen.png\" style=“width:42px;height:42px;border:0;\">', '<p>Ugri\'s 2v2 Challenge</p>\r\n\r\n<p>Round 3</p>\r\n\r\n<p>Best of 1</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/cryptlord.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/blademaster.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/shadowshaman.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/archmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/paladin.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p><u>\r\nMaps\r\n</p></u>\r\n<p>Sanctuary of Sargeras</p>', 6, ''),
(36, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/ANaDKwVM7Vw\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Lucifer <img src=\"img/warcrafticons/undead/ghoul.png\" style=\"width:42px;height:42px;border:0;\"> & WhO <img src=\"img/warcrafticons/orc/grunt.png\" style=\"width:42px;height:42px;border:0;\"> vs Bizzare <img src=\"img/warcrafticons/orc/grunt.png\" style=“width:42px;height:42px;border:0;\"> & Maru <img src=\"img/warcrafticons/human/footmen.png\" style=“width:42px;height:42px;border:0;\">', '<p>Ugri\'s 2v2 Challenge</p>\r\n\r\n<p>Round 4</p>\r\n\r\n<p>Best of 1</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/cryptlord.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/taurenchief.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/shadowshaman.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/orc/farseer.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/taurenchief.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/archmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/bloodmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p><u>\r\nMaps\r\n</p></u>\r\n<p>Ruins of Alterac</p>', 6, ''),
(37, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/0nskOQq1sWM\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Happy <img src=\"img/warcrafticons/undead/ghoul.png\" style=\"width:42px;height:42px;border:0;\"> & Cash <img src=\"img/warcrafticons/orc/grunt.png\" style=\"width:42px;height:42px;border:0;\"> vs Thorzain <img src=\"img/warcrafticons/human/footmen.png\" style=“width:42px;height:42px;border:0;\"> & StarShaped <img src=\"img/warcrafticons/nightelf/archer.png\" style=“width:42px;height:42px;border:0;\">', '<p>Ugri\'s 2v2 Challenge</p>\r\n\r\n<p>Round 5</p>\r\n\r\n<p>Best of 1</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/cryptlord.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/blademaster.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/shadowshaman.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/human/paladin.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/bloodmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/nightelf/priestess.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p><u>\r\nMaps\r\n</p></u>\r\n<p>Cozy Sands</p>', 6, ''),
(38, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/SKb1koSxG74\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Foggy <img src=\"img/warcrafticons/nightelf/archer.png\" style=\"width:42px;height:42px;border:0;\"> & Hawk <img src=\"img/warcrafticons/human/footmen.png\" style=\"width:42px;height:42px;border:0;\"> vs Neytpoh <img src=\"img/warcrafticons/nightelf/archer.png\" style=“width:42px;height:42px;border:0;\"> & Shocker <img src=\"img/warcrafticons/undead/ghoul.png\" style=“width:42px;height:42px;border:0;\">', '<p>Ugri\'s 2v2 Challenge</p>\r\n\r\n<p>Round 6</p>\r\n\r\n<p>Best of 1</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/archmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/paladin.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/darkranger.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p><u>\r\nMaps\r\n</p></u>\r\n<p>Hellfire Plateau</p>', 6, ''),
(39, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/ofcuhJagLCI\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Happy <img src=\"img/warcrafticons/undead/ghoul.png\" style=\"width:42px;height:42px;border:0;\"> & Cash <img src=\"img/warcrafticons/orc/grunt.png\" style=\"width:42px;height:42px;border:0;\"> vs Neytpoh <img src=\"img/warcrafticons/nightelf/archer.png\" style=“width:42px;height:42px;border:0;\"> & Shocker <img src=\"img/warcrafticons/undead/ghoul.png\" style=“width:42px;height:42px;border:0;\">', '<p>Ugri\'s 2v2 Challenge</p>\r\n\r\n<p>Semifinal</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/cryptlord.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/farseer.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/shadowshaman.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/cryptlord.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/darkranger.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p><u>\r\nMaps\r\n</p></u>\r\n<p>Cozy Sands</p>\r\n<p>Hellfire Plateau</p>', 6, ''),
(40, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/7goWJfT0N8k\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Thorzain <img src=\"img/warcrafticons/human/footmen.png\" style=\"width:42px;height:42px;border:0;\"> & StarShaped <img src=\"img/warcrafticons/nightelf/archer.png\" style=\"width:42px;height:42px;border:0;\"> vs DowaQ <img src=\"img/warcrafticons/nightelf/archer.png\" style=“width:42px;height:42px;border:0;\"> & Fhra <img src=\"img/warcrafticons/orc/grunt.png\" style=“width:42px;height:42px;border:0;\">', '<p>Ugri\'s 2v2 Challenge</p>\r\n\r\n<p>Semifinal</p>\r\n\r\n<p>Best of 3</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/human/paladin.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/bloodmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/archmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/firelord.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/nightelf/priestess.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/taurenchief.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/shadowshaman.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p><u>\r\nMaps\r\n</p></u>\r\n<p>Hellfire Plateau</p>\r\n<p>Ruins of Alterac</p>', 6, ''),
(41, '<iframe width=\"100%\" height=\"315\" src=\"https://www.youtube.com/embed/7KEinM8HU9w\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Happy <img src=\"img/warcrafticons/undead/ghoul.png\" style=\"width:42px;height:42px;border:0;\"> & Cash <img src=\"img/warcrafticons/orc/grunt.png\" style=\"width:42px;height:42px;border:0;\"> vs Thorzain <img src=\"img/warcrafticons/human/footmen.png\" style=“width:42px;height:42px;border:0;\"> & StarShaped <img src=\"img/warcrafticons/nightelf/archer.png\" style=“width:42px;height:42px;border:0;\">', '<p>Ugri\'s 2v2 Challenge</p>\r\n\r\n<p>Grand Final</p>\r\n\r\n<p>Best of 5</p>\r\n\r\n<p><u>\r\nHeroes Used\r\n</p></u>\r\n<p>\r\n<img src=\"img/warcrafticons/undead/deathknight.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/lich.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/undead/cryptlord.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/taurenchief.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/orc/farseer.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p>\r\n</p>\r\n<p>\r\n<img src=\"img/warcrafticons/human/paladin.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/human/bloodmage.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/nightelf/keeper.png\" style=\"width:25px;height:25px;border:0;\">\r\n<img src=\"img/warcrafticons/neutral/alchemist.png\" style=\"width:25px;height:25px;border:0;\">\r\n</p>\r\n<p><u>\r\nMaps\r\n</p></u>\r\n<p>Sherbrooke Hills</p>\r\n<p>Sanctuary of Sargeras</p>\r\n<p>Southfury River</p>\r\n<p>Cozy Sands</p>\r\n<p>Hellfire Plateau</p>', 6, '');

-- --------------------------------------------------------

--
-- Table structure for table `ListOfTournaments`
--

CREATE TABLE `ListOfTournaments` (
  `TournamentID` int(11) NOT NULL,
  `TournamentName` text NOT NULL,
  `TournamentDate` varchar(255) NOT NULL,
  `TournamentStatus` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `ListOfTournaments`
--

INSERT INTO `ListOfTournaments` (`TournamentID`, `TournamentName`, `TournamentDate`, `TournamentStatus`) VALUES
(1, 'Warcraft Gold League 2018 Winter Season', '28/11/2018', 'Completed'),
(2, 'NeXT 2018 Winter', '15/12/2018', 'Completed'),
(3, 'One Belt One Road', '21/12/2018', 'Completed'),
(4, 'W-League 2018 Super League', '8/10/2018', 'Ongoing'),
(5, 'Super WGL', 'Unknown', 'Completed'),
(6, 'Ugri\'s 2v2 Challenge', '9/2/2019', 'Completed');

-- --------------------------------------------------------

--
-- Table structure for table `Reviews`
--

CREATE TABLE `Reviews` (
  `ReviewID` int(11) NOT NULL,
  `ReviewScore` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `Users`
--

CREATE TABLE `Users` (
  `userid` int(255) NOT NULL,
  `useremail` varchar(255) NOT NULL,
  `userpass` varchar(255) NOT NULL,
  `str` varchar(255) NOT NULL,
  `adminstatus` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `Users`
--

INSERT INTO `Users` (`userid`, `useremail`, `userpass`, `str`, `adminstatus`) VALUES
(1, 'alexlawrie123@gmail.com', 'YWMa0M4qOenQ6', 'YWxleA==', 'NO'),
(2, 'dave@dave.dave', 'YWosMXdYmG3XM', 'YWxleA==', 'NO');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`adminid`);

--
-- Indexes for table `FrontPage`
--
ALTER TABLE `FrontPage`
  ADD PRIMARY KEY (`frontpageid`);

--
-- Indexes for table `ListOfTournaments`
--
ALTER TABLE `ListOfTournaments`
  ADD PRIMARY KEY (`TournamentID`);

--
-- Indexes for table `Reviews`
--
ALTER TABLE `Reviews`
  ADD PRIMARY KEY (`ReviewID`);

--
-- Indexes for table `Users`
--
ALTER TABLE `Users`
  ADD PRIMARY KEY (`userid`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `adminid` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
--
-- AUTO_INCREMENT for table `FrontPage`
--
ALTER TABLE `FrontPage`
  MODIFY `frontpageid` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;
--
-- AUTO_INCREMENT for table `ListOfTournaments`
--
ALTER TABLE `ListOfTournaments`
  MODIFY `TournamentID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;
--
-- AUTO_INCREMENT for table `Reviews`
--
ALTER TABLE `Reviews`
  MODIFY `ReviewID` int(11) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `Users`
--
ALTER TABLE `Users`
  MODIFY `userid` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
